import React from 'react';
import {
    AlertCircle,
    AlertTriangle,
    ArrowLeft,
    ArrowRight,
    Bell,
    Calendar,
    Check,
    ChevronLeft,
    ChevronRight,
    CreditCard,
    Download,
    Edit3,
    Eye,
    File,
    FileDown,
    FileUp,
    Filter,
    Folder,
    Heart,
    Home,
    Info,
    Lock,
    LogIn,
    LogOut,
    Mail,
    MessageCircle,
    Phone,
    Plus,
    Printer,
    Rocket,
    RotateCcw,
    Save,
    Search,
    Settings,
    Share2,
    ShoppingCart,
    Star,
    ThumbsDown,
    ThumbsUp,
    Trash2,
    Unlock,
    Upload,
    User,
    X,
} from 'lucide-react';
import type { ButtonPreset, IconMapping } from '../types/Button.types';

export const defaultIconMapping: IconMapping = {
    // Base icons with fa prefix
    faCheck: <Check size={16} />,
    faExclamationTriangle: <AlertTriangle size={16} />,
    faExclamationCircle: <AlertCircle size={16} />,
    faInfoCircle: <Info size={16} />,
    faSave: <Save size={16} />,
    faTrash: <Trash2 size={16} />,
    faEdit: <Edit3 size={16} />,
    faPlus: <Plus size={16} />,
    faDownload: <Download size={16} />,
    faUpload: <Upload size={16} />,
    faSearch: <Search size={16} />,
    faFilter: <Filter size={16} />,
    faRefresh: <RotateCcw size={16} />,
    faArrowLeft: <ArrowLeft size={16} />,
    faArrowRight: <ArrowRight size={16} />,
    faChevronLeft: <ChevronLeft size={16} />,
    faChevronRight: <ChevronRight size={16} />,
    faTimes: <X size={16} />,
    faRocket: <Rocket size={16} />,
    faEye: <Eye size={16} />,
    faHome: <Home size={16} />,
    faUser: <User size={16} />,
    faCog: <Settings size={16} />,
    faHeart: <Heart size={16} />,
    faStar: <Star size={16} />,
    faPhone: <Phone size={16} />,
    faEnvelope: <Mail size={16} />,
    faCalendar: <Calendar size={16} />,
    faFile: <File size={16} />,
    faFolder: <Folder size={16} />,
    faLock: <Lock size={16} />,
    faUnlock: <Unlock size={16} />,
    faShoppingCart: <ShoppingCart size={16} />,
    faBell: <Bell size={16} />,
    faComment: <MessageCircle size={16} />,
    faShare: <Share2 size={16} />,
    faThumbsUp: <ThumbsUp size={16} />,
    faThumbsDown: <ThumbsDown size={16} />,

    // Simple aliases
    check: <Check size={16} />,
    save: <Save size={16} />,
    delete: <Trash2 size={16} />,
    edit: <Edit3 size={16} />,
    add: <Plus size={16} />,
    plus: <Plus size={16} />,
    download: <Download size={16} />,
    upload: <Upload size={16} />,
    search: <Search size={16} />,
    filter: <Filter size={16} />,
    refresh: <RotateCcw size={16} />,
    back: <ArrowLeft size={16} />,
    next: <ArrowRight size={16} />,
    close: <X size={16} />,
    rocket: <Rocket size={16} />,
    eye: <Eye size={16} />,
    view: <Eye size={16} />,
    home: <Home size={16} />,
    user: <User size={16} />,
    settings: <Settings size={16} />,
    heart: <Heart size={16} />,
    star: <Star size={16} />,
    phone: <Phone size={16} />,
    email: <Mail size={16} />,
    mail: <Mail size={16} />,
    calendar: <Calendar size={16} />,
    file: <File size={16} />,
    folder: <Folder size={16} />,
    lock: <Lock size={16} />,
    unlock: <Unlock size={16} />,
    cart: <ShoppingCart size={16} />,
    bell: <Bell size={16} />,
    notification: <Bell size={16} />,
    comment: <MessageCircle size={16} />,
    share: <Share2 size={16} />,
    like: <ThumbsUp size={16} />,
    dislike: <ThumbsDown size={16} />,
};

export const defaultPresets: Record<string, ButtonPreset> = {
    addToCart: {
        icon: <ShoppingCart size={16} />,
        label: 'Aggiungi al Carrello',
        variant: 'primary',
    },
    checkout: {
        icon: <CreditCard size={16} />,
        label: 'Procedi al Pagamento',
        variant: 'success',
    },
    wishlist: {
        icon: <Heart size={16} />,
        label: 'Aggiungi ai Preferiti',
        variant: 'outline-primary',
    },
    login: {
        icon: <LogIn size={16} />,
        label: 'Accedi',
        variant: 'primary',
    },
    logout: {
        icon: <LogOut size={16} />,
        label: 'Esci',
        variant: 'outline-secondary',
    },
    profile: {
        icon: <User size={16} />,
        label: 'Profilo',
        variant: 'secondary',
    },
    export: {
        icon: <FileDown size={16} />,
        label: 'Esporta',
        variant: 'outline-info',
    },
    import: {
        icon: <FileUp size={16} />,
        label: 'Importa',
        variant: 'outline-info',
    },
    print: {
        icon: <Printer size={16} />,
        label: 'Stampa',
        variant: 'outline-secondary',
    },
    email: {
        icon: <Mail size={16} />,
        label: 'Invia Email',
        variant: 'outline-primary',
    },
    share: {
        icon: <Share2 size={16} />,
        label: 'Condividi',
        variant: 'outline-secondary',
    },
    comment: {
        icon: <MessageCircle size={16} />,
        label: 'Commenta',
        variant: 'outline-primary',
    },
    save: {
        icon: <Save size={16} />,
        label: 'Salva',
        variant: 'success',
    },
    cancel: {
        icon: <X size={16} />,
        label: 'Annulla',
        variant: 'outline-secondary',
    },
    delete: {
        icon: <Trash2 size={16} />,
        label: 'Elimina',
        variant: 'danger',
    },
};