import type { Device } from "@store_admin/devices/devices.types.ts";
import type { FormData } from "./deviceEditForm.types";

export const deviceToFormData = (d: Device): FormData => ({
  machine_Name: d.machine_Name || "",
  waste: d.waste || "",
  status: d.status ?? 0,
  linuxVersion: d.linux_Version || "",
  startAvailable: d.start_Available || "",
  endAvailable: d.end_Available || "",
  street: d.street || "",
  postalCode: d.postal_Code || "",
  province: d.province || "",
  city: d.city || "",
  country: d.country || "",
  municipality: d.municipality || "",
  address: d.address || "",
  tatus_ready_d75_3_7: d.status_READY_D75_3_7 || false,
  status_Machine_Blocked: d.status_Machine_Blocked || false,
  codiceGps: d.codice_Gps || "",
  sheetName: d.sheet_Name || "",
  customerName: d.customer_Name || "",
  matricolaBte: d.matricola_Bte || "",
  matricolaKgn: d.matricola_Kgn || "",
  customer: d.customer || "",
  ip_Router: d.ip_Router || "",
  gpsX: d.gps_x || "",
  gpsY: d.gps_y || "",
  note: d.note || "",
});

export const formDataToDevice = (f: FormData) => ({
  machine_Name: f.machine_Name,
  waste: f.waste || null,
  status: f.status,
  linux_Version: f.linuxVersion || null,
  start_Available: f.startAvailable || null,
  end_Available: f.endAvailable || null,
  street: f.street || null,
  postal_Code: f.postalCode || null,
  province: f.province || null,
  city: f.city || null,
  country: f.country || null,
  municipality: f.municipality || null,
  address: f.address || null,
  status_READY_D75_3_7: f.tatus_ready_d75_3_7,
  status_Machine_Blocked: f.status_Machine_Blocked,
  codice_Gps: f.codiceGps || null,
  sheet_Name: f.sheetName || null,
  customer_Name: f.customerName || null,
  matricola_Bte: f.matricolaBte || null,
  matricola_Kgn: f.matricolaKgn || null,
  customer: f.customer || null,
  ip_Router: f.ip_Router || null,
  gps_x: f.gpsX || null,
  gps_y: f.gpsY || null,
  note: f.note || null,
});
