import type { FilterConfig } from "@utils/types/filters.types.ts";

export const DeviceFields = {
  SEARCH: "search",
  WASTE: "waste",
  STATUS: "status",
  CITY: "city",
  PROVINCE: "province",
  CUSTOMER: "customer_Name",
  STATUS_MACHINE_BLOCKED: "status_machine_blocked",
  STATUS_READY: "status_ready_d75_3_7",
} as const;

export const createDevicesFilterConfig = ({
  filters,
  setFilter,
}): FilterConfig[] => [
  {
    key: DeviceFields.SEARCH,
    type: "name",
    label: "Ricerca",
    name: DeviceFields.SEARCH,
    placeholder: "Nome macchina, cliente, città...",
    value: filters[DeviceFields.SEARCH] || "",
    onChange: (e) => setFilter(DeviceFields.SEARCH, e.target?.value || e),
  },
  {
    key: DeviceFields.WASTE,
    type: "select",
    label: "Tipo Rifiuto",
    name: DeviceFields.WASTE,
    placeholder: "Tutti i tipi",
    value: filters[DeviceFields.WASTE] || "",
    onChange: (value) => setFilter(DeviceFields.WASTE, value),
    options: [
      { label: "Tutti i tipi", value: "" },
      { label: "Plastica", value: "Plastica" },
      { label: "Secco", value: "Secco" },
      { label: "Umido", value: "Umido" },
      { label: "Vetro", value: "Vetro" },
      { label: "Indifferenziato", value: "Indifferenziato" },
      { label: "Carta", value: "Carta" },
      { label: "VPL", value: "vpl" },
    ],
  },
  {
    key: DeviceFields.STATUS,
    type: "select",
    label: "Stato",
    name: DeviceFields.STATUS,
    placeholder: "Tutti gli stati",
    value: filters[DeviceFields.STATUS] || "",
    onChange: (value) => setFilter(DeviceFields.STATUS, value),
    options: [
      { label: "Tutti gli stati", value: "" },
      { label: "Attivo", value: "1" },
      { label: "Inattivo", value: "0" },
    ],
  },
  {
    key: DeviceFields.CITY,
    type: "name",
    label: "Città",
    name: DeviceFields.CITY,
    placeholder: "Inserisci città",
    value: filters[DeviceFields.CITY] || "",
    onChange: (e) => setFilter(DeviceFields.CITY, e.target?.value || e),
  },
  {
    key: DeviceFields.PROVINCE,
    type: "name",
    label: "Provincia",
    name: DeviceFields.PROVINCE,
    placeholder: "Inserisci provincia",
    value: filters[DeviceFields.PROVINCE] || "",
    onChange: (e) => setFilter(DeviceFields.PROVINCE, e.target?.value || e),
  },
  {
    key: DeviceFields.CUSTOMER,
    type: "name",
    label: "Cliente",
    name: DeviceFields.CUSTOMER,
    placeholder: "Inserisci cliente",
    value: filters[DeviceFields.CUSTOMER] || "",
    onChange: (e) => setFilter(DeviceFields.CUSTOMER, e.target?.value || e),
  },
  {
    key: DeviceFields.STATUS_MACHINE_BLOCKED,
    type: "select",
    label: "Stato Blocco",
    name: DeviceFields.STATUS_MACHINE_BLOCKED,
    placeholder: "Tutti",
    value: filters[DeviceFields.STATUS_MACHINE_BLOCKED] || "",
    onChange: (value) => setFilter(DeviceFields.STATUS_MACHINE_BLOCKED, value),
    options: [
      { label: "Tutti", value: "" },
      { label: "Bloccato", value: "true" },
      { label: "Non Bloccato", value: "false" },
    ],
  },
];
